# docker-compose.yml
version: '3.4'
services:
  frontend-client:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-client
    ports:
      - "3000:5000"
  frontend-client-admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-client-admin
    ports:
      - "3001:5000"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8080:8080"